### ISSUE TITLE
After attempt to load invalid unit, fleet still tries to fetch state, even after unload/destroy

### ISSUE THREAD

**Issue by 3onyc** [coreos/fleet#793]
After trying to load an invalid unit (In this case a template unit) the following errors repeat continuously, even after unload/destroy.

Fleet version: 0.6.2

```
generator.go:41] Failed fetching current unit states: Unit name backup-nginx@.service is not valid.
reconcile.go:151] Unable to determine agent's current state: failed fetching unit states: Unit name backup-nginx@.service is not valid.
```

**Comment by balboah** [comment]
destroy and restart doesn't seem to fix this issue for me.
still looping with that kind of error log. As well as blocking forever if I try starting @1 for that template

**Comment by danielwhatmuff** [comment]
I am seeing this behaviour on fleet 0.10.2. Have tried fleetctl destroy / unload and restarting the fleet service. Was this closed due to inactivity or was there a fix?

**Comment by danielwhatmuff** [comment]
ERROR reconcile.go:79 Unable to determine agent's current states from UnitManager: Unit name search@.service is not valid.

**Comment by mischief** [comment]
@danielwhatmuff see #1236

**Comment by wptad** [comment]
I think the problem is fleet doesn't clean its old units.

I solve it by this:

```
# 
sudo rm /run/fleet/units/BAD_UNIT.service
sudo rm /run/systemd/system/BAD_UNIT.service
sudo systemctl restart fleet

```

**Comment by mischief** [comment]
now that 0.11.4 is in the alpha image, this should never happen again as it is prevented at the fleetd api level. please open another ticket if you continue to have the problem.

**Comment by luebken** [comment]
@wptad fix worked for me although I had to stop fleet before. so for the sake of completeness: 

```
sudo systemctl stop fleet
sudo rm /run/fleet/units/BAD_UNIT.service
sudo rm /run/systemd/system/BAD_UNIT.service
sudo systemctl restart fleet
```

**Comment by ivankennethwang** [comment]
happened to me on 

$ fleetctl --version
fleetctl version 0.11.5

```
Mar 24 03:45:03 xxx fleetd[884]: ERROR reconcile.go:79: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name xxx@.service is not valid.
Mar 24 03:45:03 xxx fleetd[884]: ERROR generator.go:65: Failed fetching current unit states: Unit name xxx@.service is not valid.
Mar 24 03:45:04 xxx fleetd[884]: ERROR generator.go:65: Failed fetching current unit states: Unit name xxx@.service is not valid.
Mar 24 03:45:05 xxx fleetd[884]: ERROR generator.go:65: Failed fetching current unit states: Unit name xxx@.service is not valid.
```

fixed by doing steps shown by @luebken

**Comment by cneth** [comment]
We are also still seeing this with Fleet version 0.11.5 - a template unit was submitted without a parameter and this resulted in a stuck unit on all the nodes:

ERROR generator.go:65: Failed fetching current unit states: Unit name v-2-2-testS3-short@.service is not valid.

This is an easy mistake to make and a somewhat painful one to recover from.  It would be good to get this corrected.

**Comment by dongsupark** [comment]
@cneth I just saw this comment, and tried to reproduce this error with the current master. No luck. Maybe it's not enough to just submit an invalid template file. It would be a lot easier to debug if I could know a simple way to reproduce it.
